version: "3"
services:
  db:
    image: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pdfa
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d