version: "3"

x-template: &flyway-template
  image: boxfuse/flyway:latest
  volumes:
    - ./src/main/resources/db/migration:/flyway/sql
    - ./:/flyway/conf
  depends_on:
    - db

services:
  flyway-clean:
    <<: *flyway-template
    command: clean

  flyway-migrate:
    <<: *flyway-template
    command: migrate

  db:
    image: postgres:13.2-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: spap
      POSTGRES_PASSWORD: spap
      POSTGRES_DB: springapp
    #      volumes:
    #        - ./postgres:/docker-entrypoint-initdb.d
    container_name: spring_app_db
