# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
executors:
  build-container:
    docker:
      - image: circleci/openjdk:11
  test-container:
    docker:
      - image: circleci/openjdk:11
      - image: circleci/postgres:11-ram
        environment:
          TEST_DATABASE_URL:
          POSTGRES_USER: spap
          POSTGRES_DB: springapp
          POSTGRES_PASSWORD: spap

jobs:
  build:
    executor: build-container
    working_directory: ~/repo
    environment:
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
    steps:
      - checkout
      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle" }}
      - run:
          name: Install dependencies
          command: ./gradlew build -x test
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-cache-{{ checksum "build.gradle" }}
      - persist_to_workspace:
          root: .
          paths:
            - build

  test:
    executor: test-container
    working_directory: ~/repo
    environment:
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: postgresql-client install
          command: |
            sudo rm -rf /var/lib/apt/lists/*
            sudo apt update
            sudo apt install postgresql-client-11
      - run:
          name: flyway migrate
          command: |
            ./gradlew flywayClean
            ./gradlew flywayMigrate -Penv=develop
      - run:
          name: db-init
          command: |
            psql
            -d "postgresql://postgres@localhost:5432/postgres"
            -f "postgres/init.sql"
      - run:
          name: test-run
          command: |
            ./gradlew test

workflows:
  version: 2
  workflow:
    jobs:
      - build
      - test:
          requires:
            - build
    # - deploy:
    #     requires:
    #       - test
